version: '3'
services:
  clientapp-consul:
    image: consul
    depends_on:
    - clientapp
    networks:
      consul-net:
        ipv4_address: 172.18.1.101
    container_name: clientapp-consul
    environment:
        - CONSUL_BIND_INTERFACE=eth0
        - CONSUL_CLIENT_INTERFACE=eth0
    command: "agent -join=172.18.0.2 -datacenter=us_west -log-level=debug"